apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: nodejs
          image: acrrathore.azurecr.io/nodejsdocker1:latest
          command:
            [
              "powershell",
              "-Command",
              "npm install; npm run lint; npm test; npm start",
            ]
          ports:
            - containerPort: 3000
      tolerations:
        - key: "os"
          operator: "Equal"
          value: "windows"
          effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 3000
